[tool.black]
exclude = '''
(
  /(
      \.eggs        # exclude a few common directories in the
    | \.git         # root of the project
    | \.benchmark
    | \.mypy_cache
    | \.pytest_cache
    | build
    | dist
  )/
)
'''
include = '\.py?$'
line-length = 120
skip-string-normalization = true
target-version = ['py311']
