# Generated by Django 4.1.7 on 2023-03-28 13:55
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('pokemon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeGroup',
        ),
        migrations.AlterField(
            model_name='usertype',
            name='group_type',
            field=models.ManyToManyField(to='pokemon.typegroup'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='poke_type', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
